file:"C:\\ProgramData/Git/config"	core.symlinks=false
file:"C:\\ProgramData/Git/config"	core.autocrlf=true
file:"C:\\ProgramData/Git/config"	core.fscache=true
file:"C:\\ProgramData/Git/config"	color.diff=auto
file:"C:\\ProgramData/Git/config"	color.status=auto
file:"C:\\ProgramData/Git/config"	color.branch=auto
file:"C:\\ProgramData/Git/config"	color.interactive=true
file:"C:\\ProgramData/Git/config"	help.format=html
file:"C:\\ProgramData/Git/config"	rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig	credential.helper=manager
file:C:/Users/Dylan/.gitconfig	user.name=dlafonta
file:C:/Users/Dylan/.gitconfig	user.email=dlafonta@eecs.wsu.edu
file:C:/Users/Dylan/.gitconfig	user.signingkey=A69CC4FD27772642
file:C:/Users/Dylan/.gitconfig	credential.helper=manager
file:C:/Users/Dylan/.gitconfig	core.safecrlf=false
file:C:/Users/Dylan/.gitconfig	core.autocrlf=false
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/wsu-cpts489-fa20/bp-sslive.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.master.remote=origin
file:.git/config	branch.master.merge=refs/heads/master
file:.git/config	branch.feature.remote=origin
file:.git/config	branch.feature.merge=refs/heads/feature
